language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: tRvRX051HQv1N2uW0U1ahtoD2uOlBc21YKa/DdsvcIfQh9FzNGkpTi2PNQYM+W5sKJJLc6jhjhE3n3vsW16EXXZpid/0GYRAkEWdrgZVqqcY4Zr4zCmPJQ/MuGZjMhXoQ7ryICk1ytj4vE3sEPJQucJxium2X8HJJUHzcpsPRxtE17NJSdU1eXbWqHfe+SWU98LJj0XDeMhm0yaX11DtxSxNjmiafO1tcUTMoxQHd/vrOvc4JZ3J6Gb7GXKmiYO8Sm0jGO42XB6RJ3na6uS7rzkugZCESfkPgk0hvYsDPtyTbLW7bo/0kAaE1NyFizA7xHO63LYD/tL0iM8tw8D8UErvh4N6hR/GuYmkrPdZjiACjiAB63LgiCdI9DW0WnfVFOzXrJCH33QbaEenusxWyJyNYKjYDOOreXNvN5GQ+w7eHKZDKhgvWxmaPOq3vjqTnf/cZmed3eYq+UohzwrRo4uUokOCHZT6RfdsYlu7X9ntbFxqLqtUG30FsED58gcBaW4MqgQGIPdhhFGukPoUUemChEO+OVGeHcnIsQFQTje9FCzNHaf/wwuXM/qgAi/U4jEricwobhBSKpQSxNP9ICXyqR0pQnjBuc6eYIA7GqEWKA+eOTA/azPRQt7oXaKSCh8PxIYGuwZNMKOw99xlZIPWPCwrnondoOhrnpevhfc=
  - secure: Tq3jbnteYCEKYdYhDVuxDLnLfNJmajYNJLLDcB141KlaCaUFmeS7H6fUkTzlgjzKZe2PzATDQVkP8zdzwa8FmhzUHQAV8KiiLIZkG/lpF9ITf8a5h9X+ge9QTX7YvS9wDCyiay3reoW3F3f9Juguwv1rWy3OLimD2F88LahzINXOk/L0EYRbDbEYCfyDiuAGfWOjIi0Sy890SgqM0ZIqkW4dfI/DAzWVGsVR5U+tQt+R/Q/l6UaEpeErjY6yQgXxqiVGBZAiejuE2AtHzxyNJRcK4QLcXvg/Hc2ZPrbZ9psUUeMNDw6LQdxfzJ/YLyoERnpqO7zTMUP+E2upTsVBDT9/jj4RYJd91xUzMd1sPDpiIXABiNuJz5rV2atOI591OtnOjYkPwLnimFyBCFrfAsi3I/pEQbE6xjonTAd8v+xbNYTKPpMmdor+ZOIvEsJ7wmVgmLLhAU1aPqbxxBDJWFJE+klvYX/kcGQ6cZmppUrm+e/NUmEP0tHYZvulC1RSMo7HfmWUy9oRAE5LqzrkinDB4WWrcg/L9MWVYXg39+h5ksDbASr2JQCZ6fB9FNJkwFxqkKWSQUMiJR/KGU5blbQ7RRlaZBk7QPiTHtg4iRAkNtX9aS4BfN5d7G3OagZFv4LdSS5Byc8viRDeRx6Jujl30Nqnyuk2FamI06t4dwM=
